
import { SectionWrapper } from '@/components/layout/section-wrapper';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Image from 'next/image';
import Link from 'next/link';
import { Briefcase, ExternalLink, Github } from 'lucide-react';

// Helper function to generate slugs (you might want to move this to a utils file)
const generateSlug = (title: string) => title.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');

export const projectsData = [
  {
    id: generateSlug('Pneumatic Soft Gripper'),
    title: 'Pneumatic Soft Gripper',
    description: 'Design and development of soft robotic gripper for the purpose of manipulating plastic straws. Actuator parameters optimized and selected through parameter sweeping. Resin molds fabricated and gripper prototyped with performance evaluated.',
    imageUrl: '/images/GripperCover.jpg',
    imageHint: 'robotic gripper',
    liveLink: '#',
    githubLink: '#',
    tags: ['Soft Robotics', 'MATLAB Parallel Computing', 'Parameter Optimization', 'FDM 3D Printing', 'Resin Molding'],
    objective: 'This project focused on the design, modeling, and fabrication of a soft, fiber-reinforced pneumatic actuator gripper capable of lifting a plastic straw from a flat surface without damaging them. The developed solution is intended to test functionality prior to integration into a manufacturing assembly line. A fiber reinforced soft actuator was the prescribed solution. This design uses a soft body with a thin inextensible layer along the base. The whole design is wrapped in a fiber to prevent ballooning.',
    requirements: [
      'Grip Straw of 7mm',
      'Retain grip throughout handling',
      'Grip force does not collapse straw',
      'Design utilizes soft fiber reinforced actuator structure',
      'Pressure delivered via medical syringe'
    ],
    technicalProcess: [
      {
        title: 'Define Design Constraints',
        description: 'Define operational constraints that describe a functioning actuator. These included the actuation force, the actuators ability to grip the straw, and a lack of contact with the ground during operation amongst other things.'
      },
      {
        title: 'Establish Actuator Length Parameter Sweep',
        description: 'To define the length of a functional actuator, a zero thickness constant curvature trajectory model was created in MATLAB. Trajectories were swept in parallel across actuator length and xy position, with successful contact with the bottom half of the target being logged. Additionally, successful configurations had maximum width calculated by finding the minimum value for the normal distance from the end effector to the x axis.',
        images: [
            { src: '/images/BendAngle.png', alt: 'Bend Angle vs Pressure', hint: 'graph plot' },
        ]
      },
      {
        title: 'Cross-Sectional Parameter Sweep',
        description: 'The cross sectional dimensions of air chamber radius, base thickness and top thickness required definition next. A potential configuration space was generated by performing a 3 dimensional sweep with a defined target force and bend angle using a Quasi-Static Fiber Soft Actuator Model developed by Polygerinos et al.',
        images: [
          { src: '/images/CrossSection.JPG', alt: 'Cross Section of Actuator', hint: 'technical drawing' }
        ]
      },
      {
        title: 'Actuator Design',
        description: 'Actuator dimensions that minimized thickness while maximizing output forces were selected from the configuration spaces. From these dimensions an initial model of the soft actuator body was constructed in SolidWorks. The design used Ecoflex 0030 for the body, polyethylene sheet for the inextensible layer and 0.3 mm nylon line for the fiber sheath. A tapered tip was added to mitigate ground contact'
      },
      {
        title: 'Mold Design and Fabrication',
        description: 'Initially a closed, vertical mold with a floating mandrel was designed and FDM 3D printed, however resin leaked through the parting lines so the design was abandoned. The revised mold was an open top horizontal design that kept the floating mandrel. This would be the design used to produce the final prototype.',
        images: [
           { src: '/images/Mold1.JPG', alt: 'Mold Design', hint: 'cad model' },
           { src: '/images/Mold2.png', alt: 'Mold Fabrication', hint: '3d printed mold' }
        ]
      },
      {
        title: 'Actuator Fabrication',
        description: 'Two part Ecoflex 0030 was mixed and poured into the open top mold with the mandrel in place. After sitting for 12 hours, the actuator was removed from the mold. With the mandrel still inserted, the inextensible layer was placed on the base and the assembly was wrapped evenly with fiber. Two actuators were affixed to a 3D printed mount and pneumatic tubing was plumbed.'
      },
      {
        title: 'Testing',
        description: 'To evaluate the effectiveness of the prototype soft gripper, grip acquisition and retention tests were performed. The design was found to be capable of lifting aligned and unaligned straws from a flat surface.'
      }
    ],
    outcomeAndImpact: 'Designed and prototyped fiber reinforced soft actuator that successfully completed intended function.\nGained valuable experience in using parallel processing to perform parameter sweeps within MATLAB.'
  },
  {
    id: 'ire-ablation-device',
    title: 'IRE Ablation Device',
    description: 'Evaluation of numerous electrode configurations for performing IRE Ablation Procedure. Electrode spacing and sizing tested using Comsol cell death modeling to optimize design. Preliminary modeling of catheter based design performed.',
    imageUrl: '/images/AblationCover.JPG',
    imageHint: 'medical ablation device',
    liveLink: '#',
    githubLink: '#',
    tags: ['Medical Device', 'Ablation Analysis', 'Comsol', 'SolidWorks Design', 'Market Research'],
    objective: 'Develop an optimal electrode configuration for performing IRE Ablation along a 2 cm section of vessel wall. The design must fit within a 3 French catheter.',
    requirements: [
      'Evenly ablate 2 cm section of cell wall',
      'Target cells have 3 - 7mm diameters',
      'Wall thickness is 25% of cell diameter',
      'Vessel wall conductivity 0.271 S/m',
      'Muscle Conductivity 0.202 S/m',
      'Blood conductivity 0.7 S/m'
    ],
    technicalProcess: [
      {
        title: 'Establish Cell Death Model',
        description: 'Created a FEA model within COMSOL that evaluated cell death based on input current, voltage, and electron configuration. Model established using biological conductivities sourced from existing research.'
      },
      {
        title: 'Evaluate Monopolar vs Bipolar Configuration',
        description: 'Utilizing custom cell death model, tested monopolar and bipolar electrode configuration for 60 and 80 pulses. Established that bipolar configuration resulted in more uniform ablation.',
        images: [
          { src: '/images/Monopolar60.png', alt: 'Monopolar Configuration 60 pulses', hint: 'FEA ablation' },
          { src: '/images/Bipolar60.png', alt: 'Bipolar Configuration 60 pulses', hint: 'FEA ablation' },
          { src: '/images/Monopolar80.png', alt: 'Monopolar Configuration 80 pulses', hint: 'FEA ablation' },
          { src: '/images/Bipolar80.png', alt: 'Bipolar Configuration 80 pulses', hint: 'FEA ablation' }
        ]
      },
      {
        title: 'Evaluate Number of Electrodes',
        description: 'Compared 4, 6, and 8 electrode bipolar configurations with optimized electron diameters. Discovered 6 electrodes was optimal for ablating the entire vessel wall without additional cell death.',
        images: [
          { src: '/images/Electrodes4.png', alt: '4 Electrodes Configuration', hint: 'FEA ablation' },
          { src: '/images/Electrodes6.png', alt: '6 Electrodes Configuration', hint: 'FEA ablation' },
          { src: '/images/Electrodes8.png', alt: '8 Electrodes Configuration', hint: 'FEA ablation' }
        ]
      },
      {
        title: 'Optimize Number of Pulses',
        description: 'Tuned number of pulses for 6 electrode bipolar configuration at 3, 5, and 7mm vessel diameters.',
        images: [
            { src: '/images/ID3mm.png', alt: '3mm Vessel Diameter', hint: 'FEA ablation' },
            { src: '/images/ID5mm.png', alt: '5mm Vessel Diameter', hint: 'FEA ablation' },
            { src: '/images/ID7mm.png', alt: '7mm Vessel Diameter', hint: 'FEA ablation' }
        ]
      },
      {
        title: 'Create Preliminary Catheter Design',
        description: 'Designed and modeled catheter to house electrodes and expand them to different vessel diameters. Electrodes intended to rest in buckled state and expand outwards as cover is retracted.',
        images: [
            { src: '/images/AblationDesign1.jpg', alt: 'Ablation Design - View 1', hint: 'catheter design' },
            { src: '/images/AblationDesign2.jpg', alt: 'Ablation Design - View 2', hint: 'medical device' },
            { src: '/images/AblationDesign3.jpg', alt: 'Ablation Design - View 3', hint: 'cad model' },
        ]
      },
      {
        title: 'Conduct Competitor Research',
        description: 'Abbott Xience Stent technology investigated and regulatory pathway taken explored to lay framework for developing a marketable product.'
      }
    ],
    outcomeAndImpact: 'Designed catheter based IRE ablation device optimized for achieving best results for target blood vessels.\nGained valuable experience in using COMSOL software.\nDeveloped understanding of regulatory pathway required to take FDA Class 3 medical device to consumer market.'
  },
  {
    id: generateSlug('Inline 12:1 Gearbox'),
    title: 'Inline 12:1 Gearbox',
    description: 'Design of compound gear train to achieve 12:1 reduction ratio within 22 millimeter casing. Gear combinations computationally established and then validated and selected using gear stress analysis. Casing modeled for selected configuration.',
    imageUrl: '/images/GearCover.jpg',
    imageHint: 'gearbox assembly',
    liveLink: '#',
    githubLink: '#',
    tags: ['Parameter Selection', 'Matlab', 'Gear Stress Calculations', 'PTC Mathcad', 'Gear Train Design', 'SolidWorks', 'Design Packaging'],
    objective: 'Design a 12:1 reduction ratio gearbox that fits within a 22 mm cylindrical package. Use gears of standard pressure angles and pitches. The gearbox would be driven by a motor w/ nominal of torque 6.96 mNm at a nominal speed of 7060 rpm.',
    requirements: [
        'Reduction ratio of 12:1 (Input:Output)',
        'Package Size: 22mm OD, 20mm Length',
        'Nominal Motor Input: Torque: 6.96mNm Speed: 7060rpm',
        'Gear Material: 1045 Steel',
        'Desired Lifespan: 1000 hours'
    ],
    technicalProcess: [
      {
        title: 'Define Design Degrees of Freedom',
        description: 'The design degrees of freedom were identified as pitch, number of teeth, face width, and individual stage ratios.'
      },
      {
        title: 'Determine Stage Permutations',
        description: 'Used prime factorization in MATLAB, to find standard ratios that reached a 12:1 reduction for 4,5 and 6 stage configurations.'
      },
      {
        title: 'Engineering Calculations',
        description: 'Gear constants for stress calculations selected. Bending and surface stress and strength compared in MATHCAD.'
      },
      {
        title: 'Selection and Modeling',
        description: 'Optimal design selected and modeled with bearings and casing. Input and output shaft aligned through canting.'
      }
    ],
    outcomeAndImpact: "Optimized solution was identified, validated and modeled.\nThrough this project experience was gained in gear train design and analysis practices."
  },
    {
    id: generateSlug('Prototype Slitting Machine'),
    title: 'Prototype Slitting Machine',
    description: 'Proof of concept manufacturing process capable of creating slits in plastic straw developed, designed, and prototyped for external customer. Project carried from concept generation to preliminary testing. Achieved 1st Place in Senior Design.',
    imageUrl: '/images/BlendyCover.JPG',
    imageHint: 'machine prototype',
    liveLink: '#',
    githubLink: '#',
    tags: ['Customer Communication', 'Scope Management', 'Process Design', 'Pneumatic Control', 'CNC Machining', '3D Printing'],
    objective: 'To build a performant and SEO-friendly platform for content creators to publish articles and engage with readers.',
    requirements: [
        'User authentication for authors.',
        'Markdown editor for writing posts.',
        'Comment system for reader interaction.',
        'Admin panel for managing posts and users.'
    ],
    technicalProcess: [
        'Used Next.js for server-side rendering and static site generation.',
        'Integrated with a headless CMS (e.g., Strapi, Contentful) via GraphQL.',
        'Implemented user authentication using NextAuth.js.'
    ],
    outcomeAndImpact: 'Provided a fast, secure, and easy-to-use blogging solution, adopted by several content creators for its modern stack and features.'
  },
  {
    id: 'angiographic-catheter', // Using pre-generated slug
    title: 'Angiographic Catheter',
    description: 'Design of angiographic balloon catheter intended for drug delivery to pulmonary arteries. Developed to functional requirements with materials sourced from commercially available suppliers.',
    imageUrl: '/images/CatheterCover.jpg',
    imageHint: 'medical catheter',
    liveLink: '#',
    githubLink: '#',
    tags: ['Catheter Design', 'Material Sourcing', 'Resilient Modeling', 'Solidworks', 'Medical Compliance', 'ISO 594'],
    objective: 'Design an angiographic catheter intended for drug delivery to the pulmonary artery. Include a balloon tip and a catheter hub that facilitates balloon inflation with a syringe.',
    requirements: [
        'Deployment to Pulmonary Artery (PA)',
        'Balloon conforms to typical diameter of PA',
        'Dual lumen catheter (Inflation and Delivery)',
        'Catheter hub w/ 2 Luer Lock ports.',
        'Required materials from reputable source'
    ],
    technicalProcess: [
      {
        title: 'Select Key Constraints',
        description: 'Important values were selected for catheter length, catheter diameter, balloon diameter and balloon shape and durometer.'
      },
      {
        title: 'Source Materials and Create BOM',
        description: 'Materials were sourced from Nordson Medical and Chamfer, a quote was generated for production cost.'
      },
      {
        title: 'Design Catheter Hub',
        description: 'Catheter hub with isolated channels and luer lock connectors was designed compliant to ISO 594.'
      },
      {
        title: 'Adjust Design for Prototyping',
        description: 'Catheter hub design was simplified and modifications were made for prototyping with 3D printing.'
      },
      {
        title: 'Generate Marketing Material',
        description: 'Catheter assembly was modeled in SolidWorks and high-quality renders were generated in Visualize.'
      }
    ],
    outcomeAndImpact: 'Researched and designed proof of concept angiographic catheter.\nPrepared design for prototyping through design changes and part sourcing.\nGained experience with designing in compliance to ISO 594'
  },
  {
    id: 'project-management-simulation',
    title: 'Project Management Simulation',
    description: 'Creation of project plan and kick off presentation covering scope, work breakdown structure, schedule, recovery, risk management and cost management for deployment of a manufacturing product line.',
    imageUrl: '/images/ManageCover.JPG',
    imageHint: 'management simulation',
    liveLink: '#',
    githubLink: '#',
    tags: ['Work Breakdown Structure', 'Project Scheduling', 'GANNT Chart', 'Recovery', 'Risk Management', 'Cost Management'],
    objective: 'Propose a simulated engineering project and create kick off material regarding key points of the project lifestyle utilizing key points learned in the project management class.',
    requirements: [
      'Chosen engineering projects must be addressable by required key project management topics.',
      'Kick off meeting must include: WBS, Budget Management, Schedule, Risk and Communication Plan',
    ],
    technicalProcess: [
      {
        title: 'Define Scope',
        description: 'For this simulation, the selected project was created from the position of a contract manufacturer tasked with establishing manufacturing capabilities for a customer with a simple multi-part assembly. The scope consisted of a revised design of the customer product specifically for manufacturing. Also called for in the scope was the deployment of a standards conforming manufacturing process and a pilot run of production.'
      },
      {
        title: 'Create Work Breakdown Structure',
        description: 'Tasks required to achieve defined scope were identified and grouped to create work breakdown structure to facilitate later creation of scheduling and tasks.',
        images: [
            { src: '/images/WBS.JPG', alt: 'Work Breakdown Structure', hint: 'gantt chart' }
        ]
      },
      {
        title: 'Generate Project Schedule and Highlight Recovery Methods',
        description: 'Utilized work breakdown structure to generate projected project schedule. Identified critical path and proposed potential recovery methods that included fast tracking, crashing, and resource reallocation to overcome unforeseen delays.',
        images: [
            { src: '/images/Schedule.png', alt: 'Project Schedule', hint: 'gantt chart' }
        ]
      },
       {
        title: 'Analyze Potential Risks',
        description: 'Created a categorized list of potential risks impacting project cost or schedule using If Then format. Quantified each risk based on the likelihood and consequence, with each scored from 1-5. Created 4 Corner Risk Chart for largest risks.',
        images: [
            { src: '/images/Risk.png', alt: 'Project Risk Analysis', hint: 'risk chart' }
        ]
      },
      {
        title: 'Estimate Project Costs',
        description: 'Established reasonable estimates for the cost of individual tasks using labor cost estimates, expected man hours, commercial rental listings, and equipment costs. Produced an overall project cost estimate.'
      },
      {
        title: 'Create Customer Communication Plan',
        description: 'Defined communication schedule assigning key meetings with task owners and stakeholders for each day of the week. Established additional meetings to monitor critical path and resource allocation.'
      }
    ],
    outcomeAndImpact: 'Presented a kickoff meeting to professor, receiving positive feedback alongside suggested improvements.\nGained valuable insight into the responsibilities of project management as well as the product development cycle.'
  },
  {
    id: generateSlug('Nonlinear Cancer Treatment Model'),
    title: 'Nonlinear Cancer Treatment Model',
    description: 'Evaluation of existing nonlinear models that simulated dynamics of cancer growth and treatment. Fixed point and bifurcation analysis conducted for untreated and chemotheraputrically treated tumors',
    imageUrl: '/images/CancerCover.JPG',
    imageHint: 'mathematical model graph',
    liveLink: '#',
    githubLink: '#',
    tags: ['Nonlinear Modeling', '3 Degrees of Freedom', 'Chemotherapy', 'Stability Analysis', 'Matlab', 'Bifurcation Study'],
    objective: 'To create a predictive model for cancer progression under various treatment regimens, aiding in the personalization of therapy.',
    requirements: [
      'Model nonlinear tumor growth dynamics.',
      'Incorporate effects of chemotherapy and immunotherapy.',
      'Parameterize the model using clinical or experimental data.',
      'Perform sensitivity analysis to identify key parameters.',
      'Simulate and compare different treatment protocols.'
    ],
    technicalProcess: [
      'Literature review of existing cancer models and treatment mechanisms.',
      'Formulation of a system of nonlinear ordinary differential equations.',
      'Implementation of the model in a computational environment (e.g., MATLAB, Python).',
      'Parameter estimation using optimization techniques.',
      'Validation of the model against known biological behaviors.',
      'Simulation of treatment scenarios and analysis of outcomes.'
    ],
    outcomeAndImpact: 'Developed a robust nonlinear model capable of simulating complex cancer dynamics and treatment responses. The model provides a framework for exploring novel therapeutic strategies and has potential to contribute to personalized medicine approaches in oncology.'
  },
   {
    id: 'ha-65-bone-screw', // Using pre-generated slug
    title: 'HA 6.5 Bone Screw',
    description: 'Feasibility of using polymer screw evaluated for pediatric fracture fixation. Bone screw designed and analyzed using computation and finite element analysis. Uniaxial tensile testing performed on prototype.',
    imageUrl: '/images/HA65Screw.jpg',
    imageHint: 'bone screw',
    liveLink: '#',
    githubLink: '#',
    tags: ['Orthopedic Design', 'SolidWorks', 'ANSYS', 'SLA 3D Printing', 'Instron Testing'],
    objective: 'Design an Orthopedic HA 6.5 cortical screw equipped with a through hole for a Kirschner wire. Prototype with SLA Resin.',
    requirements: [
      'Design to ASTM F543 - 17',
      'Manufacturable from Standard Resin on a Formlabs Form 3 printer.',
      'Withstand uniaxial pullout force of 100 N'
    ],
    technicalProcess: [
      {
        title: 'Design & Modeling',
        description: 'HA 6.5 orthopedic screw modeled in SolidWorks to ASTM F543-17 standards.'
      },
      {
        title: 'Engineering Calculations',
        description: 'Maximum k-wire hole diameter was calculated w/ a Factor of Safety of 3 using minimum tensile stress area calculations.'
      },
      {
        title: 'Finite Element Analysis',
        description: 'Explicit Dynamics FEA was performed in ANSYS to validate calculations, predict deformation and evaluate stress concentrations.'
      },
      {
        title: 'Prototyping',
        description: 'Screws SLA printed in Standard Resin on a Formlabs Form 3L. Design considerations included overhangs, engraving depth, and layer thickness.'
      },
      {
        title: 'GD&T',
        description: 'Performed visual inspection including grinding to centerline to view cross-section. Key dimensions were measured using digital calipers and tolerances recorded.'
      },
      {
        title: 'Mechanical Testing',
        description: 'Uniaxial tensile testing was conducted on Instron per ASTM Section A3. Failure modes were visually inspected, data was compared to FEA.'
      }
    ],
    outcomeAndImpact: 'Found that SLA printed resin screw was not suitable for pediatric fracture fixation due to insufficient thread strength.\nReaffirmed that FEA is a reliable predictor of physical testing outcomes when executed properly.'
  },
  {
    id: generateSlug('Catheter Hub w/ Hemostatic Lock'),
    title: 'Catheter Hub w/ Hemostatic Lock',
    description: 'Design and prototyping of catheter hub that enabled the injection of contrast while immobilizing guidewire with hemostatic lock with adherence to FDA guidelines. Physical prototype manufactured and tested.',
    imageUrl: '/images/CatheterHubCover.JPG',
    imageHint: 'catheter hub',
    liveLink: '#',
    githubLink: '#',
    tags: ['Design Requirement Matrix', 'Hemostatic Design', 'DFMEA', 'DHF Management', 'ISO 594', 'FDA 21.CFR 820.30', 'SLA 3D Printing'],
    objective: 'To design a robust adaptive controller that allows a 6 DOF robotic arm to maintain trajectory tracking accuracy despite unknown or changing dynamic parameters.',
    requirements: [
      'Controller must adapt to at least a 50% variation in payload mass.',
      'Real-time implementation with acceptable computational load.',
      'Stability guarantees for the adaptive control law.',
      'Performance comparison with conventional PID controllers.',
      'Simulation validation in MATLAB/Simulink environment.'
    ],
    technicalProcess: [
      'Derived the dynamic model of the 6 DOF robotic arm.',
      'Designed a model reference adaptive control (MRAC) scheme.',
      'Developed Lyapunov-based adaptation laws for parameter estimation.',
      'Implemented the controller and robot dynamics in Simulink.',
      'Conducted extensive simulations with varying payloads and disturbances.',
      'Analyzed controller performance in terms of tracking error and adaptation speed.'
    ],
    outcomeAndImpact: 'The adaptive controller significantly outperformed traditional PID controllers in handling payload variations, maintaining precise trajectory tracking. This work demonstrates the potential of adaptive control for enhancing robustness and versatility in industrial robotic applications.'
  }
];

// Helper function to chunk an array into smaller arrays of a specific size
function chunkArray<T>(array: T[], size: number): T[][] {
  const chunkedArr: T[][] = [];
  for (let i = 0; i < array.length; i += size) {
    chunkedArr.push(array.slice(i, i + size));
  }
  return chunkedArr;
}

export function ProjectsSection() {
  const projectChunks = chunkArray(projectsData, 3);

  return (
    <SectionWrapper id="projects" title="My Projects" icon={Briefcase} className="bg-secondary">
      <div className="space-y-12"> {/* Container for all chunks, adds space between them */}
        {projectChunks.map((chunk, chunkIndex) => (
          <div key={chunkIndex}>
            {/* 
              If you want a visible header for each group, you can add it here.
              For example: 
              <h3 className="text-2xl font-semibold mb-6 text-accent">
                Project Group {chunkIndex + 1}
              </h3>
            */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {chunk.map((project) => {
                const cardBaseClassName = `overflow-hidden shadow-lg group-hover:shadow-xl group-hover:scale-[1.01] transition-all duration-300 h-full flex flex-col rounded-lg`;
                const imageClassName = `transform group-hover:brightness-105 transition-all duration-300`;

                return (
                  <Link key={project.id} href={`/projects/${project.id}`} className="group block h-full">
                    <Card className={cardBaseClassName}>
                      <div className="relative h-48 md:h-56 w-full">
                        <Image
                          src={project.imageUrl}
                          alt={project.title}
                          layout="fill"
                          objectFit="cover"
                          data-ai-hint={project.imageHint}
                          className={imageClassName}
                        />
                      </div>
                      <div className="flex flex-col flex-grow p-6">
                        <CardHeader className="p-0 pb-4">
                          <CardTitle className="text-xl md:text-2xl text-accent">{project.title}</CardTitle>
                          <CardDescription className="text-sm text-muted-foreground pt-1 line-clamp-2">{project.tags.join(' • ')}</CardDescription>
                        </CardHeader>
                        <CardContent className="p-0 flex-grow">
                          <p className="text-foreground leading-relaxed text-sm mb-4 line-clamp-4">{project.description}</p>
                        </CardContent>
                        <CardFooter className="p-0 pt-4 flex space-x-3 mt-auto">
                          {project.liveLink && project.liveLink !== '#' && (
                            <Button
                              variant="outline"
                              size="sm"
                              className="hover:bg-accent hover:text-accent-foreground transition-colors duration-300 text-xs"
                              onClick={(e) => {
                                e.stopPropagation(); // Prevent Link navigation
                                e.preventDefault(); // Also prevent default link behavior
                                window.open(project.liveLink!, '_blank', 'noopener,noreferrer');
                              }}
                            >
                              <ExternalLink size={16} className="mr-1.5" />
                              Live Demo
                            </Button>
                          )}
                          {project.githubLink && project.githubLink !== '#' && (
                             <Button
                              variant="ghost"
                              size="sm"
                              className="text-primary hover:text-accent transition-colors duration-300 text-xs"
                              onClick={(e) => {
                                e.stopPropagation(); // Prevent Link navigation
                                e.preventDefault(); // Also prevent default link behavior
                                window.open(project.githubLink!, '_blank', 'noopener,noreferrer');
                              }}
                             >
                              <Github size={16} className="mr-1.5" />
                              View Code
                            </Button>
                          )}
                        </CardFooter>
                      </div>
                    </Card>
                  </Link>
                );
              })}
            </div>
          </div>
        ))}
      </div>
       <div className="text-center mt-12">
          <Button asChild size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90 transition-colors duration-300 shadow-md hover:shadow-lg transform hover:scale-105">
            <Link href="/projects">
              <Briefcase size={20} className="mr-2" />
              View All Projects
            </Link>
          </Button>
        </div>
    </SectionWrapper>
  );
}

    

    